[tool.poetry]
name = "final"
version = "0.1.0"
description = ""
authors = ["Johannes Roos <jhnnsrs@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
arkitekt-next = "^0.7.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
